Repository FeMeHaeJo/AI, pull requests merged in 2024-08, with the labels that each got.

#7 feat:test_server develop
  .idea/.gitignore
  .idea/bootcamprecommendtest_cosmetic.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: 🗑️ Remove

#9 feat: test server
  .idea/.gitignore
  .idea/bootcamprecommendtest_cosmetic.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  recommendation-service/app/CBR.py
  recommendation-service/app/__pycache__/CBR.cpython-310.pyc
  recommendation-service/app/__pycache__/base_skintype.cpython-310.pyc
  recommendation-service/app/__pycache__/collaborative_filtering.cpython-310.pyc
  recommendation-service/app/__pycache__/depth_skintype.cpython-310.pyc
  recommendation-service/app/__pycache__/nutr_recommendation.cpython-310.pyc
  recommendation-service/app/__pycache__/resultImage.cpython-310.pyc
  recommendation-service/app/collaborative_filtering.py
  recommendation-service/app/test.py
  requirements.txt
Labels: ♻️ Refactor

#11 refactor: 파일 인식 오류 수정
  recommendation-service/app/app.py
  requirements.txt
Labels: 🐞 BugFix

#13 Fix/server error #10
  .idea/AI.iml
  .idea/bootcamprecommendtest_cosmetic.iml
  .idea/misc.xml
  recommendation-service/app/__pycache__/CBR.cpython-310.pyc
  recommendation-service/app/__pycache__/base_skintype.cpython-310.pyc
  recommendation-service/app/__pycache__/collaborative_filtering.cpython-310.pyc
  recommendation-service/app/__pycache__/depth_skintype.cpython-310.pyc
  recommendation-service/app/__pycache__/nutr_recommendation.cpython-310.pyc
  recommendation-service/app/__pycache__/resultImage.cpython-310.pyc
  recommendation-service/app/app.py
  recommendation-service/data/uploaded_image.jpg
Labels: 🐞 BugFix

#14 refactor: ultralytics버전 수정 및 디버깅 코드 추가
  recommendation-service/app/__pycache__/depth_skintype.cpython-310.pyc
  recommendation-service/app/depth_skintype.py
  requirements.txt
Labels: 🐞 BugFix, ✅ Test
